# Generated by Django 4.2.7 on 2024-02-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
