# Generated by Django 4.2.7 on 2024-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_family_name_user_given_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.CharField(default='', max_length=60, verbose_name='성'),
        ),
        migrations.AlterField(
            model_name='user',
            name='given_name',
            field=models.CharField(default='', max_length=60, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='구글 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh-CN', '중국어'), ('zh-TW', '대만어'), ('vi', '베트남어'), ('id', '인도어'), ('th', '태국어'), ('de', '독일어'), ('ru', '러시아어'), ('es', '스페인어'), ('it', '이탈리아어'), ('fr', '프랑스어')], default='ko', max_length=10, verbose_name='선호 언어'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=60, verbose_name='닉네임'),
        ),
    ]
