# Generated by Django 4.2.7 on 2024-02-26 02:28

from django.db import migrations, models
import restaurant.models.restaurant_models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.restaurant_models.restaurant_upload_to, verbose_name='식당 이미지'),
        ),
    ]
