# Generated by Django 4.2.7 on 2024-02-26 02:48

from django.db import migrations, models
import restaurant.models.restaurant_models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_image',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.restaurant_models.menu_upload_to, verbose_name='메뉴 이미지'),
        ),
    ]
