# Generated by Django 4.2.7 on 2024-02-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_restaurant_image_menu_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(default=None, max_length=90, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(default=None, max_length=90, null=True, verbose_name='경도'),
        ),
    ]
