# Generated by Django 4.2.7 on 2024-02-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=90, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=90, verbose_name='경도'),
        ),
    ]
